# Generated by Django 5.1.4 on 2025-01-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_remove_supplier_contract_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
