# Generated by Django 5.1.4 on 2025-01-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_alter_supplier_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
    ]
