# Generated by Django 5.0.7 on 2025-01-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0006_remove_inventory_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
